/**
 * WSL Browser Shim - Generates a shell script that forwards browser-open
 * requests from WSL terminal sessions back to the T3 Code desktop app.
 *
 * When a CLI tool (e.g., `gcloud auth`) invokes `$BROWSER <url>`, the shim
 * POSTs the URL to the server's `/api/open-external` HTTP endpoint. The server
 * then broadcasts a WebSocket push to the Electron renderer, which calls
 * `shell.openExternal()` to open the URL in the host Windows browser.
 *
 * @module wslBrowserShim
 */
import { mkdirSync, writeFileSync, chmodSync } from "node:fs";
import { dirname, join } from "node:path";

export interface BrowserShimOptions {
  readonly stateDir: string;
  readonly port: number;
  readonly authToken: string;
}

/**
 * Write (or overwrite) the browser shim script and return its absolute path.
 *
 * The script is placed at `<stateDir>/bin/t3-browser` and marked executable.
 * It is regenerated on every server start so the baked-in port and auth token
 * stay current.
 */
export function ensureBrowserShim(options: BrowserShimOptions): string {
  const shimPath = join(options.stateDir, "bin", "t3-browser");
  const shimDir = dirname(shimPath);
  mkdirSync(shimDir, { recursive: true });

  // The shim is intentionally minimal — a POSIX shell script that delegates to
  // curl.  Token and port are baked in so no extra env vars (which would be
  // blocked by the T3CODE_ prefix filter) need to leak into terminal sessions.
  const script = [
    "#!/bin/sh",
    "# Auto-generated by T3 Code — do not edit.",
    "# Forwards browser-open requests to the T3 Code desktop app.",
    'URL="$1"',
    '[ -z "$URL" ] && exit 0',
    "exec curl -sf -o /dev/null -X POST \\",
    `  -H "Authorization: Bearer ${options.authToken}" \\`,
    '  --data-urlencode "url=$URL" \\',
    `  "http://127.0.0.1:${options.port}/api/open-external"`,
    "",
  ].join("\n");

  writeFileSync(shimPath, script, "utf8");
  chmodSync(shimPath, 0o755);
  return shimPath;
}
